# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
                                  "background-color:qlineargradient(spread:pad, x1:0.572, y1:0.534545, x2:1, y2:1, stop:0 rgba(85, 170, 127, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 10, 1201, 91))
        self.label.setStyleSheet("QLabel#label {\n"
                                 "    font-family: \"Times New Roman\";\n"
                                 "    font-size: 45px;\n"
                                 "    font-weight: bold;\n"
                                 "    background-color: #ffffff; /* Use the desired grey background color */\n"
                                 "    border-style: ridge;\n"
                                 "    border-width: 5px;\n"
                                 "    border-color: #000000; /* Use the desired border color */\n"
                                 "    padding: 5px;\n"
                                 "    width: 40; /* Set your desired width */\n"
                                 "}\n"
                                 "")
        self.label.setObjectName("label")
        self.ImageLabel = QtWidgets.QLabel(self.widget)
        self.ImageLabel.setGeometry(QtCore.QRect(150, 180, 331, 341))
        self.ImageLabel.setText("")
        self.ImageLabel.setObjectName("ImageLabel")
        self.browse = QtWidgets.QPushButton(self.widget)
        self.browse.setGeometry(QtCore.QRect(270, 570, 93, 28))
        self.browse.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.browse.setObjectName("browse")
        self.plantRecognized = QtWidgets.QLabel(self.widget)
        self.plantRecognized.setGeometry(QtCore.QRect(690, 120, 441, 41))
        self.plantRecognized.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.plantRecognized.setObjectName("plantRecognized")
        self.waterLabel = QtWidgets.QLabel(self.widget)
        self.waterLabel.setGeometry(QtCore.QRect(690, 170, 241, 41))
        self.waterLabel.setStyleSheet("font: 18pt \"Times New Roman\";")
        self.waterLabel.setObjectName("waterLabel")
        self.sunlightLabel = QtWidgets.QLabel(self.widget)
        self.sunlightLabel.setGeometry(QtCore.QRect(690, 370, 241, 41))
        self.sunlightLabel.setStyleSheet("font: 18pt \"Times New Roman\";")
        self.sunlightLabel.setObjectName("sunlightLabel")
        self.soilLabel = QtWidgets.QLabel(self.widget)
        self.soilLabel.setGeometry(QtCore.QRect(690, 570, 461, 41))
        self.soilLabel.setStyleSheet("font: 18pt \"Times New Roman\";")
        self.soilLabel.setObjectName("soilLabel")
        self.water = QtWidgets.QTextBrowser(self.widget)
        self.water.setGeometry(QtCore.QRect(690, 210, 471, 151))
        self.water.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.water.setObjectName("water")
        self.sunlight = QtWidgets.QTextBrowser(self.widget)
        self.sunlight.setGeometry(QtCore.QRect(690, 410, 471, 151))
        self.sunlight.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.sunlight.setObjectName("sunlight")
        self.soil = QtWidgets.QTextBrowser(self.widget)
        self.soil.setGeometry(QtCore.QRect(690, 610, 471, 151))
        self.soil.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.soil.setObjectName("soil")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">FLOWER CARE SYSTEM</span></p></body></html>"))
        self.browse.setText(_translate("Dialog", "Browse"))
        self.plantRecognized.setText(_translate("Dialog", "Plant Recognized:"))
        self.waterLabel.setText(_translate("Dialog",
                                           "<html><head/><body><p><span style=\" font-size:16pt;\">Watering Instructions:</span></p></body></html>"))
        self.sunlightLabel.setText(_translate("Dialog",
                                              "<html><head/><body><p><span style=\" font-size:16pt;\">Sunlight Instructions:</span></p></body></html>"))
        self.soilLabel.setText(_translate("Dialog",
                                          "<html><head/><body><p><span style=\" font-size:16pt;\">Soil Instructions:</span></p></body></html>"))
        self.water.setHtml(_translate("Dialog",
                                      "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                      "p, li { white-space: pre-wrap; }\n"
                                      "</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                      "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.sunlight.setHtml(_translate("Dialog",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.soil.setHtml(_translate("Dialog",
                                     "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                     "p, li { white-space: pre-wrap; }\n"
                                     "</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                     "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
